export const PATIENTS = [
  {
    _id: 1,
    patient: 'John Doe',
    vitalSigns: {
      heartRate: 75,
      respiratoryRate: 16,
      bloodPressure: '120/80',
      bodyTemperature: 98.6,
    },
    age: 35,
    status: 'Completed',
    chiefComplaint: 'Annual Checkup',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-01-05',
    timeOfVisit: '09:30 AM',
  },
  {
    _id: 2,
    patient: 'Jane Smith',
    vitalSigns: {
      heartRate: 82,
      respiratoryRate: 18,
      bloodPressure: '118/76',
      bodyTemperature: 98.2,
    },
    age: 45,
    status: 'Waiting',
    chiefComplaint: 'Fever and Cough',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-02-10',
    timeOfVisit: '02:15 PM',
  },
  {
    _id: 3,
    patient: 'David Johnson',
    vitalSigns: {
      heartRate: 65,
      respiratoryRate: 14,
      bloodPressure: '130/85',
      bodyTemperature: 98.8,
    },
    age: 28,
    status: 'Cancelled',
    chiefComplaint: 'Minor Injury',
    placeOfService: 'Online',
    dateOfVisit: '2023-03-15',
    timeOfVisit: '10:45 AM',
  },
  {
    _id: 4,
    patient: 'Emily Brown',
    vitalSigns: {
      heartRate: 90,
      respiratoryRate: 20,
      bloodPressure: '125/78',
      bodyTemperature: 99.1,
    },
    age: 55,
    status: 'Completed',
    chiefComplaint: 'High Blood Pressure',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-04-20',
    timeOfVisit: '01:30 PM',
  },
  {
    _id: 5,
    patient: 'Michael Wilson',
    vitalSigns: {
      heartRate: 72,
      respiratoryRate: 16,
      bloodPressure: '122/79',
      bodyTemperature: 98.5,
    },
    age: 40,
    status: 'Waiting',
    chiefComplaint: 'General Health Check',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-05-25',
    timeOfVisit: '11:00 AM',
  },
  {
    _id: 6,
    patient: 'Olivia Miller',
    vitalSigns: {
      heartRate: 78,
      respiratoryRate: 18,
      bloodPressure: '130/85',
      bodyTemperature: 98.7,
    },
    age: 32,
    status: 'Completed',
    chiefComplaint: 'Pregnancy Checkup',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-06-30',
    timeOfVisit: '03:45 PM',
  },
  {
    _id: 7,
    patient: 'William Davis',
    vitalSigns: {
      heartRate: 88,
      respiratoryRate: 22,
      bloodPressure: '118/76',
      bodyTemperature: 99.0,
    },
    age: 50,
    status: 'Cancelled',
    chiefComplaint: 'Flu Symptoms',
    placeOfService: 'Online',
    dateOfVisit: '2023-07-05',
    timeOfVisit: '09:20 AM',
  },
  {
    _id: 8,
    patient: 'Sophia White',
    vitalSigns: {
      heartRate: 68,
      respiratoryRate: 14,
      bloodPressure: '125/78',
      bodyTemperature: 98.4,
    },
    age: 60,
    status: 'Waiting',
    chiefComplaint: 'Arthritis Consultation',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-08-10',
    timeOfVisit: '10:00 AM',
  },
  {
    _id: 9,
    patient: 'Daniel Taylor',
    vitalSigns: {
      heartRate: 75,
      respiratoryRate: 16,
      bloodPressure: '120/80',
      bodyTemperature: 98.6,
    },
    age: 45,
    status: 'Completed',
    chiefComplaint: 'Back Pain',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-09-15',
    timeOfVisit: '02:45 PM',
  },
  {
    _id: 10,
    patient: 'Ava Anderson',
    vitalSigns: {
      heartRate: 82,
      respiratoryRate: 18,
      bloodPressure: '118/76',
      bodyTemperature: 98.2,
    },
    age: 28,
    status: 'Cancelled',
    chiefComplaint: 'Allergy Symptoms',
    placeOfService: 'Online',
    dateOfVisit: '2023-10-20',
    timeOfVisit: '11:30 AM',
  },
  {
    _id: 11,
    patient: 'Ethan Moore',
    vitalSigns: {
      heartRate: 65,
      respiratoryRate: 14,
      bloodPressure: '130/85',
      bodyTemperature: 98.8,
    },
    age: 35,
    status: 'Waiting',
    chiefComplaint: 'Eye Irritation',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-11-25',
    timeOfVisit: '09:15 AM',
  },
  {
    _id: 12,
    patient: 'Isabella King',
    vitalSigns: {
      heartRate: 90,
      respiratoryRate: 20,
      bloodPressure: '125/78',
      bodyTemperature: 99.1,
    },
    age: 48,
    status: 'Completed',
    chiefComplaint: 'Diabetes Management',
    placeOfService: 'Face to Face',
    dateOfVisit: '2023-12-30',
    timeOfVisit: '01:00 PM',
  },
];
